### ISSUE TITLE
Money constructor with default currency rounds amount

### ISSUE THREAD

**Issue by michaeldileo** [DynamicHands/NodaMoney#85]
I'm not sure if this is intentional, but I only caught this in unit tests while trying to progressively build up a money object in a custom json converter. This seems like a bug, in that I never asked it to round the currency. It seems like if a user wants it to round, the user should explicitly use the rounding constructor or call a round function

![image](https://user-images.githubusercontent.com/77022818/119547120-507ce200-bd5a-11eb-95b5-a9f04f58f5c9.png)

**Comment by josefblaha** [comment]
That's because your second block uses wrong currency, an empty one.

The NodaMoney library generally rounds amounts according to currency. Each currency specifies, how much decimal places it supports. For example `Currency.FromCode("USD").DecimalDigits` returns `2`, because the smallest unit of US dollar is one cent.

In your example, you create an empty `Money` structure, which has an empty `Currency` structure. `new Money().Currency.DecimalDigits` returns `0`. Therefore your amount gets rounded to 11.

**Comment by michaeldileo** [comment]
Oh, that makes sense now. Thank you!
